/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1213-MIB"
 * 	found in "RFC1213-MIB.asn1"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_PhysAddress_H_
#define	_PhysAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PhysAddress */
typedef OCTET_STRING_t	 PhysAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PhysAddress;
asn_struct_free_f PhysAddress_free;
asn_struct_print_f PhysAddress_print;
asn_constr_check_f PhysAddress_constraint;
ber_type_decoder_f PhysAddress_decode_ber;
der_type_encoder_f PhysAddress_encode_der;
xer_type_decoder_f PhysAddress_decode_xer;
xer_type_encoder_f PhysAddress_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PhysAddress_H_ */
