/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1155-SMI"
 * 	found in "RFC1155-SMI.asn1"
 * 	`asn1c -S /home/faust/software/asn1c/skeletons/ -fcompound-names -fwide-types`
 */

#include "ApplicationSyntax.h"

static asn_oer_constraints_t asn_OER_type_ApplicationSyntax_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_ApplicationSyntax_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  4 }	/* (0..4) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ApplicationSyntax_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ApplicationSyntax, choice.address),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_NetworkAddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"address"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ApplicationSyntax, choice.counter),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Counter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"counter"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ApplicationSyntax, choice.gauge),
		(ASN_TAG_CLASS_APPLICATION | (2 << 2)),
		0,
		&asn_DEF_Gauge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gauge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ApplicationSyntax, choice.ticks),
		(ASN_TAG_CLASS_APPLICATION | (3 << 2)),
		0,
		&asn_DEF_TimeTicks,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ticks"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ApplicationSyntax, choice.arbitrary),
		(ASN_TAG_CLASS_APPLICATION | (4 << 2)),
		0,
		&asn_DEF_Opaque,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"arbitrary"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ApplicationSyntax_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 0, 0, 0 }, /* internet */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 1, 0, 0 }, /* counter */
    { (ASN_TAG_CLASS_APPLICATION | (2 << 2)), 2, 0, 0 }, /* gauge */
    { (ASN_TAG_CLASS_APPLICATION | (3 << 2)), 3, 0, 0 }, /* ticks */
    { (ASN_TAG_CLASS_APPLICATION | (4 << 2)), 4, 0, 0 } /* arbitrary */
};
asn_CHOICE_specifics_t asn_SPC_ApplicationSyntax_specs_1 = {
	sizeof(struct ApplicationSyntax),
	offsetof(struct ApplicationSyntax, _asn_ctx),
	offsetof(struct ApplicationSyntax, present),
	sizeof(((struct ApplicationSyntax *)0)->present),
	asn_MAP_ApplicationSyntax_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ApplicationSyntax = {
	"ApplicationSyntax",
	"ApplicationSyntax",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_ApplicationSyntax_constr_1, &asn_PER_type_ApplicationSyntax_constr_1, CHOICE_constraint },
	asn_MBR_ApplicationSyntax_1,
	5,	/* Elements count */
	&asn_SPC_ApplicationSyntax_specs_1	/* Additional specs */
};

