/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1213-MIB"
 * 	found in "RFC1213-MIB.asn1"
 * 	`asn1c -S /home/faust/software/asn1c/skeletons/ -fcompound-names -fwide-types`
 */

#include "AtEntry.h"

static asn_TYPE_member_t asn_MBR_AtEntry_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AtEntry, atIfIndex),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"atIfIndex"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AtEntry, atPhysAddress),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_PhysAddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"atPhysAddress"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AtEntry, atNetAddress),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_NetworkAddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"atNetAddress"
		},
};
static const ber_tlv_tag_t asn_DEF_AtEntry_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AtEntry_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* atIfIndex */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* atPhysAddress */
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 2, 0, 0 } /* internet */
};
static asn_SEQUENCE_specifics_t asn_SPC_AtEntry_specs_1 = {
	sizeof(struct AtEntry),
	offsetof(struct AtEntry, _asn_ctx),
	asn_MAP_AtEntry_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AtEntry = {
	"AtEntry",
	"AtEntry",
	&asn_OP_SEQUENCE,
	asn_DEF_AtEntry_tags_1,
	sizeof(asn_DEF_AtEntry_tags_1)
		/sizeof(asn_DEF_AtEntry_tags_1[0]), /* 1 */
	asn_DEF_AtEntry_tags_1,	/* Same as above */
	sizeof(asn_DEF_AtEntry_tags_1)
		/sizeof(asn_DEF_AtEntry_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AtEntry_1,
	3,	/* Elements count */
	&asn_SPC_AtEntry_specs_1	/* Additional specs */
};

