/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1213-MIB"
 * 	found in "RFC1213-MIB.asn1"
 * 	`asn1c -S /home/faust/software/asn1c/skeletons/ -fcompound-names -fwide-types`
 */

#include "EgpNeighEntry.h"

static asn_TYPE_member_t asn_MBR_EgpNeighEntry_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EgpNeighEntry, egpNeighState),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"egpNeighState"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EgpNeighEntry, egpNeighAddr),
		(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
		0,
		&asn_DEF_IpAddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"egpNeighAddr"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EgpNeighEntry, egpNeighAs),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"egpNeighAs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EgpNeighEntry, egpNeighInMsgs),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Counter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"egpNeighInMsgs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EgpNeighEntry, egpNeighInErrs),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Counter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"egpNeighInErrs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EgpNeighEntry, egpNeighOutMsgs),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Counter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"egpNeighOutMsgs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EgpNeighEntry, egpNeighOutErrs),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Counter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"egpNeighOutErrs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EgpNeighEntry, egpNeighInErrMsgs),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Counter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"egpNeighInErrMsgs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EgpNeighEntry, egpNeighOutErrMsgs),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Counter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"egpNeighOutErrMsgs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EgpNeighEntry, egpNeighStateUps),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Counter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"egpNeighStateUps"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EgpNeighEntry, egpNeighStateDowns),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Counter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"egpNeighStateDowns"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EgpNeighEntry, egpNeighIntervalHello),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"egpNeighIntervalHello"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EgpNeighEntry, egpNeighIntervalPoll),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"egpNeighIntervalPoll"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EgpNeighEntry, egpNeighMode),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"egpNeighMode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EgpNeighEntry, egpNeighEventTrigger),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"egpNeighEventTrigger"
		},
};
static const ber_tlv_tag_t asn_DEF_EgpNeighEntry_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EgpNeighEntry_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 5 }, /* egpNeighState */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -1, 4 }, /* egpNeighAs */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 11, -2, 3 }, /* egpNeighIntervalHello */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 12, -3, 2 }, /* egpNeighIntervalPoll */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 13, -4, 1 }, /* egpNeighMode */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 14, -5, 0 }, /* egpNeighEventTrigger */
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 1, 0, 0 }, /* egpNeighAddr */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 3, 0, 7 }, /* egpNeighInMsgs */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 4, -1, 6 }, /* egpNeighInErrs */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 5, -2, 5 }, /* egpNeighOutMsgs */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 6, -3, 4 }, /* egpNeighOutErrs */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 7, -4, 3 }, /* egpNeighInErrMsgs */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 8, -5, 2 }, /* egpNeighOutErrMsgs */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 9, -6, 1 }, /* egpNeighStateUps */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 10, -7, 0 } /* egpNeighStateDowns */
};
static asn_SEQUENCE_specifics_t asn_SPC_EgpNeighEntry_specs_1 = {
	sizeof(struct EgpNeighEntry),
	offsetof(struct EgpNeighEntry, _asn_ctx),
	asn_MAP_EgpNeighEntry_tag2el_1,
	15,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EgpNeighEntry = {
	"EgpNeighEntry",
	"EgpNeighEntry",
	&asn_OP_SEQUENCE,
	asn_DEF_EgpNeighEntry_tags_1,
	sizeof(asn_DEF_EgpNeighEntry_tags_1)
		/sizeof(asn_DEF_EgpNeighEntry_tags_1[0]), /* 1 */
	asn_DEF_EgpNeighEntry_tags_1,	/* Same as above */
	sizeof(asn_DEF_EgpNeighEntry_tags_1)
		/sizeof(asn_DEF_EgpNeighEntry_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_EgpNeighEntry_1,
	15,	/* Elements count */
	&asn_SPC_EgpNeighEntry_specs_1	/* Additional specs */
};

