/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1213-MIB"
 * 	found in "RFC1213-MIB.asn1"
 * 	`asn1c -S /home/faust/software/asn1c/skeletons/ -fcompound-names -fwide-types`
 */

#include "IfEntry.h"

static asn_TYPE_member_t asn_MBR_IfEntry_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifIndex),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifIndex"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifDescr),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_DisplayString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifDescr"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifType),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifMtu),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifMtu"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifSpeed),
		(ASN_TAG_CLASS_APPLICATION | (2 << 2)),
		0,
		&asn_DEF_Gauge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifSpeed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifPhysAddress),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_PhysAddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifPhysAddress"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifAdminStatus),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifAdminStatus"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifOperStatus),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifOperStatus"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifLastChange),
		(ASN_TAG_CLASS_APPLICATION | (3 << 2)),
		0,
		&asn_DEF_TimeTicks,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifLastChange"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifInOctets),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Counter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifInOctets"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifInUcastPkts),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Counter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifInUcastPkts"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifInNUcastPkts),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Counter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifInNUcastPkts"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifInDiscards),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Counter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifInDiscards"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifInErrors),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Counter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifInErrors"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifInUnknownProtos),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Counter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifInUnknownProtos"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifOutOctets),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Counter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifOutOctets"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifOutUcastPkts),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Counter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifOutUcastPkts"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifOutNUcastPkts),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Counter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifOutNUcastPkts"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifOutDiscards),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Counter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifOutDiscards"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifOutErrors),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Counter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifOutErrors"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifOutQLen),
		(ASN_TAG_CLASS_APPLICATION | (2 << 2)),
		0,
		&asn_DEF_Gauge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifOutQLen"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IfEntry, ifSpecific),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ifSpecific"
		},
};
static const ber_tlv_tag_t asn_DEF_IfEntry_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IfEntry_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 4 }, /* ifIndex */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -1, 3 }, /* ifType */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, -2, 2 }, /* ifMtu */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 6, -3, 1 }, /* ifAdminStatus */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 7, -4, 0 }, /* ifOperStatus */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 1 }, /* ifDescr */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 5, -1, 0 }, /* ifPhysAddress */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 21, 0, 0 }, /* ifSpecific */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 9, 0, 10 }, /* ifInOctets */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 10, -1, 9 }, /* ifInUcastPkts */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 11, -2, 8 }, /* ifInNUcastPkts */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 12, -3, 7 }, /* ifInDiscards */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 13, -4, 6 }, /* ifInErrors */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 14, -5, 5 }, /* ifInUnknownProtos */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 15, -6, 4 }, /* ifOutOctets */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 16, -7, 3 }, /* ifOutUcastPkts */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 17, -8, 2 }, /* ifOutNUcastPkts */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 18, -9, 1 }, /* ifOutDiscards */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 19, -10, 0 }, /* ifOutErrors */
    { (ASN_TAG_CLASS_APPLICATION | (2 << 2)), 4, 0, 1 }, /* ifSpeed */
    { (ASN_TAG_CLASS_APPLICATION | (2 << 2)), 20, -1, 0 }, /* ifOutQLen */
    { (ASN_TAG_CLASS_APPLICATION | (3 << 2)), 8, 0, 0 } /* ifLastChange */
};
static asn_SEQUENCE_specifics_t asn_SPC_IfEntry_specs_1 = {
	sizeof(struct IfEntry),
	offsetof(struct IfEntry, _asn_ctx),
	asn_MAP_IfEntry_tag2el_1,
	22,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_IfEntry = {
	"IfEntry",
	"IfEntry",
	&asn_OP_SEQUENCE,
	asn_DEF_IfEntry_tags_1,
	sizeof(asn_DEF_IfEntry_tags_1)
		/sizeof(asn_DEF_IfEntry_tags_1[0]), /* 1 */
	asn_DEF_IfEntry_tags_1,	/* Same as above */
	sizeof(asn_DEF_IfEntry_tags_1)
		/sizeof(asn_DEF_IfEntry_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_IfEntry_1,
	22,	/* Elements count */
	&asn_SPC_IfEntry_specs_1	/* Additional specs */
};

