/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1213-MIB"
 * 	found in "RFC1213-MIB.asn1"
 * 	`asn1c -S /home/faust/software/asn1c/skeletons/ -fcompound-names -fwide-types`
 */

#include "IpAddrEntry.h"

static int
memb_ipAdEntReasmMaxSize_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_ipAdEntReasmMaxSize_constr_6 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65535) */,
	-1};
static asn_per_constraints_t asn_PER_memb_ipAdEntReasmMaxSize_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_IpAddrEntry_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IpAddrEntry, ipAdEntAddr),
		(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
		0,
		&asn_DEF_IpAddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipAdEntAddr"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpAddrEntry, ipAdEntIfIndex),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipAdEntIfIndex"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpAddrEntry, ipAdEntNetMask),
		(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
		0,
		&asn_DEF_IpAddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipAdEntNetMask"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpAddrEntry, ipAdEntBcastAddr),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipAdEntBcastAddr"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpAddrEntry, ipAdEntReasmMaxSize),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_ipAdEntReasmMaxSize_constr_6, &asn_PER_memb_ipAdEntReasmMaxSize_constr_6,  memb_ipAdEntReasmMaxSize_constraint_1 },
		0, 0, /* No default value */
		"ipAdEntReasmMaxSize"
		},
};
static const ber_tlv_tag_t asn_DEF_IpAddrEntry_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IpAddrEntry_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 2 }, /* ipAdEntIfIndex */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, -1, 1 }, /* ipAdEntBcastAddr */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, -2, 0 }, /* ipAdEntReasmMaxSize */
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 0, 0, 1 }, /* ipAdEntAddr */
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 2, -1, 0 } /* ipAdEntNetMask */
};
static asn_SEQUENCE_specifics_t asn_SPC_IpAddrEntry_specs_1 = {
	sizeof(struct IpAddrEntry),
	offsetof(struct IpAddrEntry, _asn_ctx),
	asn_MAP_IpAddrEntry_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_IpAddrEntry = {
	"IpAddrEntry",
	"IpAddrEntry",
	&asn_OP_SEQUENCE,
	asn_DEF_IpAddrEntry_tags_1,
	sizeof(asn_DEF_IpAddrEntry_tags_1)
		/sizeof(asn_DEF_IpAddrEntry_tags_1[0]), /* 1 */
	asn_DEF_IpAddrEntry_tags_1,	/* Same as above */
	sizeof(asn_DEF_IpAddrEntry_tags_1)
		/sizeof(asn_DEF_IpAddrEntry_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_IpAddrEntry_1,
	5,	/* Elements count */
	&asn_SPC_IpAddrEntry_specs_1	/* Additional specs */
};

