/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1213-MIB"
 * 	found in "RFC1213-MIB.asn1"
 * 	`asn1c -S /home/faust/software/asn1c/skeletons/ -fcompound-names -fwide-types`
 */

#include "IpNetToMediaEntry.h"

static asn_TYPE_member_t asn_MBR_IpNetToMediaEntry_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IpNetToMediaEntry, ipNetToMediaIfIndex),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipNetToMediaIfIndex"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpNetToMediaEntry, ipNetToMediaPhysAddress),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_PhysAddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipNetToMediaPhysAddress"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpNetToMediaEntry, ipNetToMediaNetAddress),
		(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
		0,
		&asn_DEF_IpAddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipNetToMediaNetAddress"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpNetToMediaEntry, ipNetToMediaType),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipNetToMediaType"
		},
};
static const ber_tlv_tag_t asn_DEF_IpNetToMediaEntry_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IpNetToMediaEntry_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* ipNetToMediaIfIndex */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, -1, 0 }, /* ipNetToMediaType */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* ipNetToMediaPhysAddress */
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 2, 0, 0 } /* ipNetToMediaNetAddress */
};
static asn_SEQUENCE_specifics_t asn_SPC_IpNetToMediaEntry_specs_1 = {
	sizeof(struct IpNetToMediaEntry),
	offsetof(struct IpNetToMediaEntry, _asn_ctx),
	asn_MAP_IpNetToMediaEntry_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_IpNetToMediaEntry = {
	"IpNetToMediaEntry",
	"IpNetToMediaEntry",
	&asn_OP_SEQUENCE,
	asn_DEF_IpNetToMediaEntry_tags_1,
	sizeof(asn_DEF_IpNetToMediaEntry_tags_1)
		/sizeof(asn_DEF_IpNetToMediaEntry_tags_1[0]), /* 1 */
	asn_DEF_IpNetToMediaEntry_tags_1,	/* Same as above */
	sizeof(asn_DEF_IpNetToMediaEntry_tags_1)
		/sizeof(asn_DEF_IpNetToMediaEntry_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_IpNetToMediaEntry_1,
	4,	/* Elements count */
	&asn_SPC_IpNetToMediaEntry_specs_1	/* Additional specs */
};

