/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1213-MIB"
 * 	found in "RFC1213-MIB.asn1"
 * 	`asn1c -S /home/faust/software/asn1c/skeletons/ -fcompound-names -fwide-types`
 */

#include "IpRouteEntry.h"

static asn_TYPE_member_t asn_MBR_IpRouteEntry_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IpRouteEntry, ipRouteDest),
		(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
		0,
		&asn_DEF_IpAddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipRouteDest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpRouteEntry, ipRouteIfIndex),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipRouteIfIndex"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpRouteEntry, ipRouteMetric1),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipRouteMetric1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpRouteEntry, ipRouteMetric2),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipRouteMetric2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpRouteEntry, ipRouteMetric3),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipRouteMetric3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpRouteEntry, ipRouteMetric4),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipRouteMetric4"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpRouteEntry, ipRouteNextHop),
		(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
		0,
		&asn_DEF_IpAddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipRouteNextHop"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpRouteEntry, ipRouteType),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipRouteType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpRouteEntry, ipRouteProto),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipRouteProto"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpRouteEntry, ipRouteAge),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipRouteAge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpRouteEntry, ipRouteMask),
		(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
		0,
		&asn_DEF_IpAddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipRouteMask"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpRouteEntry, ipRouteMetric5),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipRouteMetric5"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpRouteEntry, ipRouteInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipRouteInfo"
		},
};
static const ber_tlv_tag_t asn_DEF_IpRouteEntry_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IpRouteEntry_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 8 }, /* ipRouteIfIndex */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -1, 7 }, /* ipRouteMetric1 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, -2, 6 }, /* ipRouteMetric2 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, -3, 5 }, /* ipRouteMetric3 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 5, -4, 4 }, /* ipRouteMetric4 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 7, -5, 3 }, /* ipRouteType */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 8, -6, 2 }, /* ipRouteProto */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 9, -7, 1 }, /* ipRouteAge */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 11, -8, 0 }, /* ipRouteMetric5 */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 12, 0, 0 }, /* ipRouteInfo */
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 0, 0, 2 }, /* ipRouteDest */
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 6, -1, 1 }, /* ipRouteNextHop */
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 10, -2, 0 } /* ipRouteMask */
};
static asn_SEQUENCE_specifics_t asn_SPC_IpRouteEntry_specs_1 = {
	sizeof(struct IpRouteEntry),
	offsetof(struct IpRouteEntry, _asn_ctx),
	asn_MAP_IpRouteEntry_tag2el_1,
	13,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_IpRouteEntry = {
	"IpRouteEntry",
	"IpRouteEntry",
	&asn_OP_SEQUENCE,
	asn_DEF_IpRouteEntry_tags_1,
	sizeof(asn_DEF_IpRouteEntry_tags_1)
		/sizeof(asn_DEF_IpRouteEntry_tags_1[0]), /* 1 */
	asn_DEF_IpRouteEntry_tags_1,	/* Same as above */
	sizeof(asn_DEF_IpRouteEntry_tags_1)
		/sizeof(asn_DEF_IpRouteEntry_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_IpRouteEntry_1,
	13,	/* Elements count */
	&asn_SPC_IpRouteEntry_specs_1	/* Additional specs */
};

