/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1155-SMI"
 * 	found in "RFC1155-SMI.asn1"
 * 	`asn1c -S /home/faust/software/asn1c/skeletons/ -fcompound-names -fwide-types`
 */

#include "ObjectName.h"

/*
 * This type is implemented using OBJECT_IDENTIFIER,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_ObjectName_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (6 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ObjectName = {
	"ObjectName",
	"ObjectName",
	&asn_OP_OBJECT_IDENTIFIER,
	asn_DEF_ObjectName_tags_1,
	sizeof(asn_DEF_ObjectName_tags_1)
		/sizeof(asn_DEF_ObjectName_tags_1[0]), /* 1 */
	asn_DEF_ObjectName_tags_1,	/* Same as above */
	sizeof(asn_DEF_ObjectName_tags_1)
		/sizeof(asn_DEF_ObjectName_tags_1[0]), /* 1 */
	{ 0, 0, OBJECT_IDENTIFIER_constraint },
	0, 0,	/* No members */
	0	/* No specifics */
};

