/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SMUX"
 * 	found in "SMUX.asn1"
 * 	`asn1c -S /home/faust/software/asn1c/skeletons/ -fcompound-names -fwide-types`
 */

#include "OpenPDU.h"

static asn_oer_constraints_t asn_OER_type_OpenPDU_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_OpenPDU_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_OpenPDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct OpenPDU, choice.simple),
		(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
		0,
		&asn_DEF_SimpleOpen,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"simple"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_OpenPDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 0, 0, 0 } /* simple */
};
asn_CHOICE_specifics_t asn_SPC_OpenPDU_specs_1 = {
	sizeof(struct OpenPDU),
	offsetof(struct OpenPDU, _asn_ctx),
	offsetof(struct OpenPDU, present),
	sizeof(((struct OpenPDU *)0)->present),
	asn_MAP_OpenPDU_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_OpenPDU = {
	"OpenPDU",
	"OpenPDU",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_OpenPDU_constr_1, &asn_PER_type_OpenPDU_constr_1, CHOICE_constraint },
	asn_MBR_OpenPDU_1,
	1,	/* Elements count */
	&asn_SPC_OpenPDU_specs_1	/* Additional specs */
};

