/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_IfEntry;
extern struct asn_TYPE_descriptor_s asn_DEF_AtEntry;
extern struct asn_TYPE_descriptor_s asn_DEF_IpAddrEntry;
extern struct asn_TYPE_descriptor_s asn_DEF_IpRouteEntry;
extern struct asn_TYPE_descriptor_s asn_DEF_IpNetToMediaEntry;
extern struct asn_TYPE_descriptor_s asn_DEF_TcpConnEntry;
extern struct asn_TYPE_descriptor_s asn_DEF_UdpEntry;
extern struct asn_TYPE_descriptor_s asn_DEF_EgpNeighEntry;
extern struct asn_TYPE_descriptor_s asn_DEF_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_SMUX_PDUs;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module RFC1213-MIB in RFC1213-MIB.asn1 */
	&asn_DEF_IfEntry,	
	&asn_DEF_AtEntry,	
	&asn_DEF_IpAddrEntry,	
	&asn_DEF_IpRouteEntry,	
	&asn_DEF_IpNetToMediaEntry,	
	&asn_DEF_TcpConnEntry,	
	&asn_DEF_UdpEntry,	
	&asn_DEF_EgpNeighEntry,	
	/* From module RFC1157-SNMP in RFC1157-SNMP.asn1 */
	&asn_DEF_Message,	
	/* From module SMUX in SMUX.asn1 */
	&asn_DEF_SMUX_PDUs,	
	0
};

