/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1155-SMI"
 * 	found in "RFC1155-SMI.asn1"
 * 	`asn1c -S /home/faust/software/asn1c/skeletons/ -fcompound-names -fwide-types`
 */

#include "SimpleSyntax.h"

static asn_oer_constraints_t asn_OER_type_SimpleSyntax_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_SimpleSyntax_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_SimpleSyntax_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SimpleSyntax, choice.number),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"number"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SimpleSyntax, choice.string),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"string"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SimpleSyntax, choice.object),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"object"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SimpleSyntax, choice.empty),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"empty"
		},
};
static const unsigned asn_MAP_SimpleSyntax_to_canonical_1[] = { 0, 1, 3, 2 };
static const unsigned asn_MAP_SimpleSyntax_from_canonical_1[] = { 0, 1, 3, 2 };
static const asn_TYPE_tag2member_t asn_MAP_SimpleSyntax_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* number */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* string */
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 3, 0, 0 }, /* empty */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 2, 0, 0 } /* object */
};
asn_CHOICE_specifics_t asn_SPC_SimpleSyntax_specs_1 = {
	sizeof(struct SimpleSyntax),
	offsetof(struct SimpleSyntax, _asn_ctx),
	offsetof(struct SimpleSyntax, present),
	sizeof(((struct SimpleSyntax *)0)->present),
	asn_MAP_SimpleSyntax_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_SimpleSyntax_to_canonical_1,
	asn_MAP_SimpleSyntax_from_canonical_1,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SimpleSyntax = {
	"SimpleSyntax",
	"SimpleSyntax",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_SimpleSyntax_constr_1, &asn_PER_type_SimpleSyntax_constr_1, CHOICE_constraint },
	asn_MBR_SimpleSyntax_1,
	4,	/* Elements count */
	&asn_SPC_SimpleSyntax_specs_1	/* Additional specs */
};

