/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SMUX"
 * 	found in "SMUX.asn1"
 * 	`asn1c -S /home/faust/software/asn1c/skeletons/ -fcompound-names -fwide-types`
 */

#include "SimpleOpen.h"

asn_TYPE_member_t asn_MBR_SimpleOpen_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SimpleOpen, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SimpleOpen, identity),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"identity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SimpleOpen, description),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_DisplayString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"description"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SimpleOpen, password),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"password"
		},
};
static const ber_tlv_tag_t asn_DEF_SimpleOpen_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SimpleOpen_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* version */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, 0, 1 }, /* description */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 3, -1, 0 }, /* password */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 1, 0, 0 } /* identity */
};
asn_SEQUENCE_specifics_t asn_SPC_SimpleOpen_specs_1 = {
	sizeof(struct SimpleOpen),
	offsetof(struct SimpleOpen, _asn_ctx),
	asn_MAP_SimpleOpen_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SimpleOpen = {
	"SimpleOpen",
	"SimpleOpen",
	&asn_OP_SEQUENCE,
	asn_DEF_SimpleOpen_tags_1,
	sizeof(asn_DEF_SimpleOpen_tags_1)
		/sizeof(asn_DEF_SimpleOpen_tags_1[0]) - 1, /* 1 */
	asn_DEF_SimpleOpen_tags_1,	/* Same as above */
	sizeof(asn_DEF_SimpleOpen_tags_1)
		/sizeof(asn_DEF_SimpleOpen_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SimpleOpen_1,
	4,	/* Elements count */
	&asn_SPC_SimpleOpen_specs_1	/* Additional specs */
};

