/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1213-MIB"
 * 	found in "RFC1213-MIB.asn1"
 * 	`asn1c -S/mnt/data/software/asn1c/skeletons -fcompound-names -fwide-types`
 */

#include "TcpConnEntry.h"

static int
memb_tcpConnLocalPort_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_tcpConnRemPort_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_TcpConnEntry_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TcpConnEntry, tcpConnState),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"tcpConnState"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TcpConnEntry, tcpConnLocalAddress),
		(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
		0,
		&asn_DEF_IpAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"tcpConnLocalAddress"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TcpConnEntry, tcpConnLocalPort),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		memb_tcpConnLocalPort_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"tcpConnLocalPort"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TcpConnEntry, tcpConnRemAddress),
		(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
		0,
		&asn_DEF_IpAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"tcpConnRemAddress"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TcpConnEntry, tcpConnRemPort),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		memb_tcpConnRemPort_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"tcpConnRemPort"
		},
};
static const ber_tlv_tag_t asn_DEF_TcpConnEntry_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TcpConnEntry_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 2 }, /* tcpConnState */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -1, 1 }, /* tcpConnLocalPort */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, -2, 0 }, /* tcpConnRemPort */
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 1, 0, 1 }, /* tcpConnLocalAddress */
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 3, -1, 0 } /* tcpConnRemAddress */
};
static asn_SEQUENCE_specifics_t asn_SPC_TcpConnEntry_specs_1 = {
	sizeof(struct TcpConnEntry),
	offsetof(struct TcpConnEntry, _asn_ctx),
	asn_MAP_TcpConnEntry_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TcpConnEntry = {
	"TcpConnEntry",
	"TcpConnEntry",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TcpConnEntry_tags_1,
	sizeof(asn_DEF_TcpConnEntry_tags_1)
		/sizeof(asn_DEF_TcpConnEntry_tags_1[0]), /* 1 */
	asn_DEF_TcpConnEntry_tags_1,	/* Same as above */
	sizeof(asn_DEF_TcpConnEntry_tags_1)
		/sizeof(asn_DEF_TcpConnEntry_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TcpConnEntry_1,
	5,	/* Elements count */
	&asn_SPC_TcpConnEntry_specs_1	/* Additional specs */
};

