/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1157-SNMP"
 * 	found in "RFC1157-SNMP.asn1"
 * 	`asn1c -S /home/faust/software/asn1c/skeletons/ -fcompound-names -fwide-types`
 */

#include "Trap-PDU.h"

asn_TYPE_member_t asn_MBR_Trap_PDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Trap_PDU, enterprise),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"enterprise"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Trap_PDU, agent_addr),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_NetworkAddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"agent-addr"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Trap_PDU, generic_trap),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"generic-trap"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Trap_PDU, specific_trap),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"specific-trap"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Trap_PDU, time_stamp),
		(ASN_TAG_CLASS_APPLICATION | (3 << 2)),
		0,
		&asn_DEF_TimeTicks,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"time-stamp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Trap_PDU, variable_bindings),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_VarBindList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"variable-bindings"
		},
};
static const ber_tlv_tag_t asn_DEF_Trap_PDU_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Trap_PDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, 0, 1 }, /* generic-trap */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, -1, 0 }, /* specific-trap */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 }, /* enterprise */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, 0, 0 }, /* variable-bindings */
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 1, 0, 0 }, /* internet */
    { (ASN_TAG_CLASS_APPLICATION | (3 << 2)), 4, 0, 0 } /* time-stamp */
};
asn_SEQUENCE_specifics_t asn_SPC_Trap_PDU_specs_1 = {
	sizeof(struct Trap_PDU),
	offsetof(struct Trap_PDU, _asn_ctx),
	asn_MAP_Trap_PDU_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Trap_PDU = {
	"Trap-PDU",
	"Trap-PDU",
	&asn_OP_SEQUENCE,
	asn_DEF_Trap_PDU_tags_1,
	sizeof(asn_DEF_Trap_PDU_tags_1)
		/sizeof(asn_DEF_Trap_PDU_tags_1[0]) - 1, /* 1 */
	asn_DEF_Trap_PDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_Trap_PDU_tags_1)
		/sizeof(asn_DEF_Trap_PDU_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Trap_PDU_1,
	6,	/* Elements count */
	&asn_SPC_Trap_PDU_specs_1	/* Additional specs */
};

