###############################################################################
# $Id: Makefile,v 1.3 2007/05/08 14:29:21 faust Exp $
###############################################################################

LIB_NAME = stg_logger
PROG = lib$(LIB_NAME)

SRCS = stg_logger.cpp

INCS = stg_logger.h

include ../Makefile.in
