include ../../Makefile.conf

LIB_NAME = stgsgcp

SRCS = proto.cpp \
       transport.cpp \
       unix.cpp \
       udp.cpp \
       tcp.cpp \
       crypto.cpp

INCS = sgcp_proto.h \
       sgcp_types.h \
       sgcp_transport.h

include ../Makefile.in
