include ../../Makefile.conf

LIB_NAME = stgsgcp

SRCS = proto.cpp \
       transport.cpp \
       unix.cpp \
       tcp.cpp \
       packet.cpp

INCS = sgcp_proto.h \
       sgcp_types.h \
       sgcp_utils.h \
       sgcp_conn.h

include ../Makefile.in
