###############################################################################
# $Id: Makefile,v 1.3 2007/05/08 14:29:20 faust Exp $
###############################################################################

LIB_NAME = hostallow
PROG = lib$(LIB_NAME)

SRCS = hostallow.cpp

INCS = hostallow.h

include ../Makefile.in
