###############################################################################
# $Id: Makefile,v 1.6 2010/01/21 13:02:12 faust Exp $
###############################################################################

LIB_NAME = script_executer
PROG = lib$(LIB_NAME)

SRCS = script_executer.cpp

INCS = script_executer.h

include ../Makefile.in
