###############################################################################
# $Id: Makefile,v 1.2 2008/12/04 17:04:41 faust Exp $
###############################################################################

include ../../../../../Makefile.conf

PROG = mod_cap_nf.so

SRCS = ./cap_nf.cpp

LIBS += $(LIB_THREAD)
STGLIBS = -lstgcommon

include ../../Makefile.in

