###############################################################################
# $Id: Makefile,v 1.10 2008/12/04 15:41:03 faust Exp $
###############################################################################

include ../../../../../Makefile.conf

PROG = mod_auth_ao.so

SRCS = ./ao.cpp

STGLIBS = scriptexecuter \
	  logger \
	  common

include ../../Makefile.in

