###############################################################################
# $Id: Makefile,v 1.11 2010/08/18 07:47:03 faust Exp $
###############################################################################

LIB_NAME = ia_auth_c
PROG = lib$(LIB_NAME)

SRCS = ia_auth_c.cpp

INCS = ia_auth_c.h

STGLIBS = -lstg_common \
	  -lstg_crypto
LIBS = $(LIB_THREAD)

include ../Makefile.in
