###############################################################################
# $Id: Makefile,v 1.4 2008/12/04 17:01:28 faust Exp $
###############################################################################

include ../../../../../Makefile.conf

PROG = mod_auth_stress.so

SRCS = ./stress.cpp

LIBS += $(LIB_THREAD)

STGLIBS = common \
	  logger \
	  scriptexecuter

include ../../Makefile.in

