###############################################################################
# $Id: Makefile,v 1.9 2010/08/18 07:47:03 faust Exp $
###############################################################################

LIB_NAME = stgjson

STGLIBS = -lstgcommon
LIBS =

SRCS =  parser.cpp \
        generator.cpp

INCS = json_parser.h \
       json_generator.h

LIB_INCS = -I ../common.lib/include

include ../Makefile.in
