/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1157-SNMP"
 * 	found in "RFC1157-SNMP.asn1"
 * 	`asn1c -fskeletons-copy`
 */

#include <asn_internal.h>

#include "Trap-PDU.h"

static asn_TYPE_member_t asn_MBR_Trap_PDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Trap_PDU, enterprise),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"enterprise"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Trap_PDU, agent_addr),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_NetworkAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"agent-addr"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Trap_PDU, generic_trap),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"generic-trap"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Trap_PDU, specific_trap),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"specific-trap"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Trap_PDU, time_stamp),
		(ASN_TAG_CLASS_APPLICATION | (3 << 2)),
		0,
		&asn_DEF_TimeTicks,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"time-stamp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Trap_PDU, variable_bindings),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_VarBindList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"variable-bindings"
		},
};
static ber_tlv_tag_t asn_DEF_Trap_PDU_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Trap_PDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, 0, 1 }, /* generic-trap at 106 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, -1, 0 }, /* specific-trap at 116 */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 }, /* enterprise at 99 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, 0, 0 }, /* variable-bindings at 125 */
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 1, 0, 0 }, /* internet at 113 */
    { (ASN_TAG_CLASS_APPLICATION | (3 << 2)), 4, 0, 0 } /* time-stamp at 120 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Trap_PDU_specs_1 = {
	sizeof(struct Trap_PDU),
	offsetof(struct Trap_PDU, _asn_ctx),
	asn_MAP_Trap_PDU_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Trap_PDU = {
	"Trap-PDU",
	"Trap-PDU",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Trap_PDU_tags_1,
	sizeof(asn_DEF_Trap_PDU_tags_1)
		/sizeof(asn_DEF_Trap_PDU_tags_1[0]) - 1, /* 1 */
	asn_DEF_Trap_PDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_Trap_PDU_tags_1)
		/sizeof(asn_DEF_Trap_PDU_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_Trap_PDU_1,
	6,	/* Elements count */
	&asn_SPC_Trap_PDU_specs_1	/* Additional specs */
};

