#! /bin/sh

# About: This script is called when user account is changed.
# Common Task: Notify about various events.
# Priority: optional

# User login
LOGIN=$1

# User parameter
PARAMETER=$2

# User parameter old value
OLDVALUE=$3

# User parameter new value
NEWVALUE=$4

# Usage examples:
#echo "User: '$LOGIN'. Parameter $PARAMETER changed from '$OLDVALUE' to '$NEWVALUE'" >> /var/stargazer/user.change.log