#! /bin/sh

# About: This script is called when the user successfully authenticated on the server.
# Common Task: Rebuild firewall to allow user to access the Internet.
# Priority: required

# User login
LOGIN=$1

# User IP
IP=$2

# User cash
CASH=$3

# User ID
ID=$4

# Selected DIRs (from rules file) to connect
DIRS=$5

# Usage examples:
#echo "Connected `date +%Y.%m.%d-%H.%M.%S` $IP $CASH" >> /var/stargazer/users/$LOGIN/connect.log