#! /bin/sh

# About: This script is called when the user wants to disconnect or authorization timeout has passed.
# Common task: Rebuild firewall to disallow user to access the Internet.
# Priority: required

# User login
LOGIN=$1

# User IP
IP=$2

# User cash
CASH=$3

# User ID
ID=$4

# Selected DIRs (from rules file) to disconnect
DIRS=$5

# Usage examples:
#echo "Disconnected `date +%Y.%m.%d-%H.%M.%S` $IP $CASH" >> /var/stargazer/users/$LOGIN/connect.log
