#! /bin/sh

# About: This script is called when the user is added to the Stargazer.
# Common task: Automate typical actions on adding user to the network,
#              such as creating email or IM account.
# Priority: optional

# User login
LOGIN=$1

# Usage examples:
#echo "Added user $login" >> /var/stargazer/add_del.log