###############################################################################
# $Id: Makefile,v 1.3 2007/05/08 14:40:09 nobunaga Exp $
###############################################################################

LIB_NAME = common_settings
PROG = lib$(LIB_NAME)

SRCS = common_settings.cpp

INCS = common_settings.h

include ../Makefile.in
