###############################################################################
# $Id: Makefile,v 1.4 2007/05/08 14:29:19 faust Exp $
###############################################################################

LIB_NAME = stgconffiles

SRCS = conffiles.cpp

INCS = conffiles.h

include ../Makefile.in
