###############################################################################
# $Id: Makefile,v 1.3 2007/05/08 14:29:19 faust Exp $
###############################################################################

LIB_NAME = dotconfpp

SRCS = dotconfpp.cpp \
       mempool.cpp

INCS = dotconfpp.h

include ../Makefile.in
