###############################################################################
# $Id: Makefile,v 1.3 2007/05/08 14:29:19 faust Exp $
###############################################################################

LIB_NAME = dotconfpp
PROG = lib$(LIB_NAME)

SRCS = dotconfpp.cpp \
       mempool.cpp

INCS = dotconfpp.h \
       mempool.h

include ../Makefile.in
