###############################################################################
# $Id: Makefile,v 1.10 2010/02/16 11:41:00 faust Exp $
###############################################################################

include ../../../../../Makefile.conf

LIBS += $(LIB_THREAD)

PROG = mod_auth_ia.so

SRCS = ./inetaccess.cpp

STGLIBS = -lstg_common -lstg_crypto

include ../../Makefile.in

