/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1155-SMI"
 * 	found in "RFC1155-SMI.asn1"
 * 	`asn1c -S/mnt/data/software/asn1c/skeletons -fcompound-names -fwide-types`
 */

#ifndef	_Counter_H_
#define	_Counter_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Counter */
typedef unsigned long	 Counter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Counter;
asn_struct_free_f Counter_free;
asn_struct_print_f Counter_print;
asn_constr_check_f Counter_constraint;
ber_type_decoder_f Counter_decode_ber;
der_type_encoder_f Counter_encode_der;
xer_type_decoder_f Counter_decode_xer;
xer_type_encoder_f Counter_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Counter_H_ */
#include <asn_internal.h>
