/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1213-MIB"
 * 	found in "RFC1213-MIB.asn1"
 * 	`asn1c -S/mnt/data/software/asn1c/skeletons -fcompound-names -fwide-types`
 */

#ifndef	_DisplayString_H_
#define	_DisplayString_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DisplayString */
typedef OCTET_STRING_t	 DisplayString_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DisplayString;
asn_struct_free_f DisplayString_free;
asn_struct_print_f DisplayString_print;
asn_constr_check_f DisplayString_constraint;
ber_type_decoder_f DisplayString_decode_ber;
der_type_encoder_f DisplayString_encode_der;
xer_type_decoder_f DisplayString_decode_xer;
xer_type_encoder_f DisplayString_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DisplayString_H_ */
#include <asn_internal.h>
