/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1155-SMI"
 * 	found in "RFC1155-SMI.asn1"
 * 	`asn1c -S /home/faust/software/asn1c/skeletons/ -fcompound-names -fwide-types`
 */

#ifndef	_Gauge_H_
#define	_Gauge_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Gauge */
typedef unsigned long	 Gauge_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Gauge_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Gauge;
extern const asn_INTEGER_specifics_t asn_SPC_Gauge_specs_1;
asn_struct_free_f Gauge_free;
asn_struct_print_f Gauge_print;
asn_constr_check_f Gauge_constraint;
ber_type_decoder_f Gauge_decode_ber;
der_type_encoder_f Gauge_encode_der;
xer_type_decoder_f Gauge_decode_xer;
xer_type_encoder_f Gauge_encode_xer;
oer_type_decoder_f Gauge_decode_oer;
oer_type_encoder_f Gauge_encode_oer;
per_type_decoder_f Gauge_decode_uper;
per_type_encoder_f Gauge_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Gauge_H_ */
#include <asn_internal.h>
