/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1157-SNMP"
 * 	found in "RFC1157-SNMP.asn1"
 * 	`asn1c -S/mnt/data/software/asn1c/skeletons -fcompound-names -fwide-types`
 */

#ifndef	_GetNextRequest_PDU_H_
#define	_GetNextRequest_PDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PDU.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GetNextRequest-PDU */
typedef PDU_t	 GetNextRequest_PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetNextRequest_PDU;
asn_struct_free_f GetNextRequest_PDU_free;
asn_struct_print_f GetNextRequest_PDU_print;
asn_constr_check_f GetNextRequest_PDU_constraint;
ber_type_decoder_f GetNextRequest_PDU_decode_ber;
der_type_encoder_f GetNextRequest_PDU_encode_der;
xer_type_decoder_f GetNextRequest_PDU_decode_xer;
xer_type_encoder_f GetNextRequest_PDU_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _GetNextRequest_PDU_H_ */
#include <asn_internal.h>
