/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1155-SMI"
 * 	found in "RFC1155-SMI.asn1"
 * 	`asn1c -S/mnt/data/software/asn1c/skeletons -fcompound-names -fwide-types`
 */

#ifndef	_NetworkAddress_H_
#define	_NetworkAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IpAddress.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NetworkAddress_PR {
	NetworkAddress_PR_NOTHING,	/* No components present */
	NetworkAddress_PR_internet
} NetworkAddress_PR;

/* NetworkAddress */
typedef struct NetworkAddress {
	NetworkAddress_PR present;
	union NetworkAddress_u {
		IpAddress_t	 internet;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NetworkAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NetworkAddress;

#ifdef __cplusplus
}
#endif

#endif	/* _NetworkAddress_H_ */
#include <asn_internal.h>
