/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1157-SNMP"
 * 	found in "RFC1157-SNMP.asn1"
 * 	`asn1c -S /home/faust/software/asn1c/skeletons/ -fcompound-names -fwide-types`
 */

#ifndef	_PDUs_H_
#define	_PDUs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GetRequest-PDU.h"
#include "GetNextRequest-PDU.h"
#include "GetResponse-PDU.h"
#include "SetRequest-PDU.h"
#include "Trap-PDU.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PDUs_PR {
	PDUs_PR_NOTHING,	/* No components present */
	PDUs_PR_get_request,
	PDUs_PR_get_next_request,
	PDUs_PR_get_response,
	PDUs_PR_set_request,
	PDUs_PR_trap
} PDUs_PR;

/* PDUs */
typedef struct PDUs {
	PDUs_PR present;
	union PDUs_u {
		GetRequest_PDU_t	 get_request;
		GetNextRequest_PDU_t	 get_next_request;
		GetResponse_PDU_t	 get_response;
		SetRequest_PDU_t	 set_request;
		Trap_PDU_t	 trap;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDUs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDUs;
extern asn_CHOICE_specifics_t asn_SPC_PDUs_specs_1;
extern asn_TYPE_member_t asn_MBR_PDUs_1[5];
extern asn_per_constraints_t asn_PER_type_PDUs_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _PDUs_H_ */
#include <asn_internal.h>
