/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SMUX"
 * 	found in "SMUX.asn1"
 * 	`asn1c -S/mnt/data/software/asn1c/skeletons -fcompound-names -fwide-types`
 */

#ifndef	_RRspPDU_H_
#define	_RRspPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRspPDU {
	RRspPDU_failure	= -1
} e_RRspPDU;

/* RRspPDU */
typedef INTEGER_t	 RRspPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRspPDU;
asn_struct_free_f RRspPDU_free;
asn_struct_print_f RRspPDU_print;
asn_constr_check_f RRspPDU_constraint;
ber_type_decoder_f RRspPDU_decode_ber;
der_type_encoder_f RRspPDU_encode_der;
xer_type_decoder_f RRspPDU_decode_xer;
xer_type_encoder_f RRspPDU_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RRspPDU_H_ */
#include <asn_internal.h>
