/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1157-SNMP"
 * 	found in "RFC1157-SNMP.asn1"
 * 	`asn1c -S /home/faust/software/asn1c/skeletons/ -fcompound-names -fwide-types`
 */

#ifndef	_SetRequest_PDU_H_
#define	_SetRequest_PDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PDU.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SetRequest-PDU */
typedef PDU_t	 SetRequest_PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetRequest_PDU;
asn_struct_free_f SetRequest_PDU_free;
asn_struct_print_f SetRequest_PDU_print;
asn_constr_check_f SetRequest_PDU_constraint;
ber_type_decoder_f SetRequest_PDU_decode_ber;
der_type_encoder_f SetRequest_PDU_encode_der;
xer_type_decoder_f SetRequest_PDU_decode_xer;
xer_type_encoder_f SetRequest_PDU_encode_xer;
oer_type_decoder_f SetRequest_PDU_decode_oer;
oer_type_encoder_f SetRequest_PDU_encode_oer;
per_type_decoder_f SetRequest_PDU_decode_uper;
per_type_encoder_f SetRequest_PDU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SetRequest_PDU_H_ */
#include <asn_internal.h>
