/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1155-SMI"
 * 	found in "RFC1155-SMI.asn1"
 * 	`asn1c -S/mnt/data/software/asn1c/skeletons -fcompound-names -fwide-types`
 */

#ifndef	_SimpleSyntax_H_
#define	_SimpleSyntax_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <OCTET_STRING.h>
#include <OBJECT_IDENTIFIER.h>
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SimpleSyntax_PR {
	SimpleSyntax_PR_NOTHING,	/* No components present */
	SimpleSyntax_PR_number,
	SimpleSyntax_PR_string,
	SimpleSyntax_PR_object,
	SimpleSyntax_PR_empty
} SimpleSyntax_PR;

/* SimpleSyntax */
typedef struct SimpleSyntax {
	SimpleSyntax_PR present;
	union SimpleSyntax_u {
		INTEGER_t	 number;
		OCTET_STRING_t	 string;
		OBJECT_IDENTIFIER_t	 object;
		NULL_t	 empty;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SimpleSyntax_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SimpleSyntax;

#ifdef __cplusplus
}
#endif

#endif	/* _SimpleSyntax_H_ */
#include <asn_internal.h>
