/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SMUX"
 * 	found in "SMUX.asn1"
 * 	`asn1c -S/mnt/data/software/asn1c/skeletons -fcompound-names -fwide-types`
 */

#ifndef	_SimpleOpen_H_
#define	_SimpleOpen_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <OBJECT_IDENTIFIER.h>
#include "DisplayString.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SimpleOpen__version {
	SimpleOpen__version_version_1	= 0
} e_SimpleOpen__version;

/* SimpleOpen */
typedef struct SimpleOpen {
	INTEGER_t	 version;
	OBJECT_IDENTIFIER_t	 identity;
	DisplayString_t	 description;
	OCTET_STRING_t	 password;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SimpleOpen_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SimpleOpen;

#ifdef __cplusplus
}
#endif

#endif	/* _SimpleOpen_H_ */
#include <asn_internal.h>
