/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1155-SMI"
 * 	found in "RFC1155-SMI.asn1"
 * 	`asn1c -S /home/faust/software/asn1c/skeletons/ -fcompound-names -fwide-types`
 */

#ifndef	_TimeTicks_H_
#define	_TimeTicks_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TimeTicks */
typedef unsigned long	 TimeTicks_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TimeTicks_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TimeTicks;
extern const asn_INTEGER_specifics_t asn_SPC_TimeTicks_specs_1;
asn_struct_free_f TimeTicks_free;
asn_struct_print_f TimeTicks_print;
asn_constr_check_f TimeTicks_constraint;
ber_type_decoder_f TimeTicks_decode_ber;
der_type_encoder_f TimeTicks_encode_der;
xer_type_decoder_f TimeTicks_decode_xer;
xer_type_encoder_f TimeTicks_encode_xer;
oer_type_decoder_f TimeTicks_decode_oer;
oer_type_encoder_f TimeTicks_encode_oer;
per_type_decoder_f TimeTicks_decode_uper;
per_type_encoder_f TimeTicks_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TimeTicks_H_ */
#include <asn_internal.h>
