/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1157-SNMP"
 * 	found in "RFC1157-SNMP.asn1"
 * 	`asn1c -S/mnt/data/software/asn1c/skeletons -fcompound-names -fwide-types`
 */

#ifndef	_Trap_PDU_H_
#define	_Trap_PDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include "NetworkAddress.h"
#include <INTEGER.h>
#include "TimeTicks.h"
#include "VarBindList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Trap_PDU__generic_trap {
	Trap_PDU__generic_trap_coldStart	= 0,
	Trap_PDU__generic_trap_warmStart	= 1,
	Trap_PDU__generic_trap_linkDown	= 2,
	Trap_PDU__generic_trap_linkUp	= 3,
	Trap_PDU__generic_trap_authenticationFailure	= 4,
	Trap_PDU__generic_trap_egpNeighborLoss	= 5,
	Trap_PDU__generic_trap_enterpriseSpecific	= 6
} e_Trap_PDU__generic_trap;

/* Trap-PDU */
typedef struct Trap_PDU {
	OBJECT_IDENTIFIER_t	 enterprise;
	NetworkAddress_t	 agent_addr;
	INTEGER_t	 generic_trap;
	INTEGER_t	 specific_trap;
	TimeTicks_t	 time_stamp;
	VarBindList_t	 variable_bindings;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Trap_PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Trap_PDU;

#ifdef __cplusplus
}
#endif

#endif	/* _Trap_PDU_H_ */
#include <asn_internal.h>
