/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1157-SNMP"
 * 	found in "RFC1157-SNMP.asn1"
 * 	`asn1c -S /home/faust/software/asn1c/skeletons/ -fcompound-names -fwide-types`
 */

#ifndef	_VarBindList_H_
#define	_VarBindList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VarBind;

/* VarBindList */
typedef struct VarBindList {
	A_SEQUENCE_OF(struct VarBind) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VarBindList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VarBindList;
extern asn_SET_OF_specifics_t asn_SPC_VarBindList_specs_1;
extern asn_TYPE_member_t asn_MBR_VarBindList_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VarBind.h"

#endif	/* _VarBindList_H_ */
#include <asn_internal.h>
