/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1155-SMI"
 * 	found in "RFC1155-SMI.asn1"
 * 	`asn1c -fskeletons-copy`
 */

#include <asn_internal.h>

#include "ObjectSyntax.h"

static asn_TYPE_member_t asn_MBR_ObjectSyntax_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectSyntax, choice.simple),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_SimpleSyntax,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"simple"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectSyntax, choice.application_wide),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ApplicationSyntax,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"application-wide"
		},
};
static asn_TYPE_tag2member_t asn_MAP_ObjectSyntax_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* number at 73 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 }, /* string at 76 */
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 0, 0, 0 }, /* empty at 82 */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 }, /* object at 79 */
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 1, 0, 0 }, /* internet at 113 */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 1, 0, 0 }, /* counter at 91 */
    { (ASN_TAG_CLASS_APPLICATION | (2 << 2)), 1, 0, 0 }, /* gauge at 94 */
    { (ASN_TAG_CLASS_APPLICATION | (3 << 2)), 1, 0, 0 }, /* ticks at 97 */
    { (ASN_TAG_CLASS_APPLICATION | (4 << 2)), 1, 0, 0 } /* arbitrary at 104 */
};
static asn_CHOICE_specifics_t asn_SPC_ObjectSyntax_specs_1 = {
	sizeof(struct ObjectSyntax),
	offsetof(struct ObjectSyntax, _asn_ctx),
	offsetof(struct ObjectSyntax, present),
	sizeof(((struct ObjectSyntax *)0)->present),
	asn_MAP_ObjectSyntax_tag2el_1,
	9,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ObjectSyntax = {
	"ObjectSyntax",
	"ObjectSyntax",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_ObjectSyntax_1,
	2,	/* Elements count */
	&asn_SPC_ObjectSyntax_specs_1	/* Additional specs */
};

