/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "SMUX"
 * 	found in "SMUX.asn1"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_OpenPDU_H_
#define	_OpenPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SimpleOpen.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OpenPDU_PR {
	OpenPDU_PR_NOTHING,	/* No components present */
	OpenPDU_PR_simple
} OpenPDU_PR;

/* OpenPDU */
typedef struct OpenPDU {
	OpenPDU_PR present;
	union OpenPDU_u {
		SimpleOpen_t	 simple;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OpenPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OpenPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _OpenPDU_H_ */
