/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1157-SNMP"
 * 	found in "RFC1157-SNMP.asn1"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_PDU_H_
#define	_PDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include "VarBindList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PDU__error_status {
	PDU__error_status_noError	= 0,
	PDU__error_status_tooBig	= 1,
	PDU__error_status_noSuchName	= 2,
	PDU__error_status_badValue	= 3,
	PDU__error_status_readOnly	= 4,
	PDU__error_status_genErr	= 5
} e_PDU__error_status;

/* PDU */
typedef struct PDU {
	INTEGER_t	 request_id;
	INTEGER_t	 error_status;
	INTEGER_t	 error_index;
	VarBindList_t	 variable_bindings;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDU;

#ifdef __cplusplus
}
#endif

#endif	/* _PDU_H_ */
