/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1157-SNMP"
 * 	found in "RFC1157-SNMP.asn1"
 * 	`asn1c -fskeletons-copy`
 */

#include <asn_internal.h>

#include "PDUs.h"

static asn_TYPE_member_t asn_MBR_PDUs_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.get_request),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_GetRequest_PDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"get-request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.get_next_request),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_GetNextRequest_PDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"get-next-request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.get_response),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_GetResponse_PDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"get-response"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.set_request),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_SetRequest_PDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"set-request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.trap),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_Trap_PDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"trap"
		},
};
static asn_TYPE_tag2member_t asn_MAP_PDUs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* get-request at 34 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* get-next-request at 37 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* get-response at 40 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* set-request at 43 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* trap at 47 */
};
static asn_CHOICE_specifics_t asn_SPC_PDUs_specs_1 = {
	sizeof(struct PDUs),
	offsetof(struct PDUs, _asn_ctx),
	offsetof(struct PDUs, present),
	sizeof(((struct PDUs *)0)->present),
	asn_MAP_PDUs_tag2el_1,
	5,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_PDUs = {
	"PDUs",
	"PDUs",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_PDUs_1,
	5,	/* Elements count */
	&asn_SPC_PDUs_specs_1	/* Additional specs */
};

