/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "SMUX"
 * 	found in "SMUX.asn1"
 * 	`asn1c -fskeletons-copy`
 */

#include <asn_internal.h>

#include "SimpleOpen.h"

static asn_TYPE_member_t asn_MBR_SimpleOpen_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SimpleOpen, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SimpleOpen, identity),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"identity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SimpleOpen, description),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_DisplayString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"description"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SimpleOpen, password),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"password"
		},
};
static ber_tlv_tag_t asn_DEF_SimpleOpen_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SimpleOpen_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* version at 59 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, 0, 1 }, /* description at 66 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 3, -1, 0 }, /* password at 69 */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 1, 0, 0 } /* identity at 63 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SimpleOpen_specs_1 = {
	sizeof(struct SimpleOpen),
	offsetof(struct SimpleOpen, _asn_ctx),
	asn_MAP_SimpleOpen_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SimpleOpen = {
	"SimpleOpen",
	"SimpleOpen",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SimpleOpen_tags_1,
	sizeof(asn_DEF_SimpleOpen_tags_1)
		/sizeof(asn_DEF_SimpleOpen_tags_1[0]) - 1, /* 1 */
	asn_DEF_SimpleOpen_tags_1,	/* Same as above */
	sizeof(asn_DEF_SimpleOpen_tags_1)
		/sizeof(asn_DEF_SimpleOpen_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_SimpleOpen_1,
	4,	/* Elements count */
	&asn_SPC_SimpleOpen_specs_1	/* Additional specs */
};

