###############################################################################
# $Id: Makefile,v 1.6 2008/12/04 17:08:56 faust Exp $
###############################################################################

include ../../../../../Makefile.conf

PROG = mod_cap_ipq.so

SRCS = ./ipq_cap.cpp \
       ./libipq.c

LIBS += $(LIB_THREAD)
STGLIBS = -lstgcommon

include ../../Makefile.in

