###############################################################################
# $Id: Makefile,v 1.9 2008/12/04 17:07:37 faust Exp $
###############################################################################

include ../../../../../Makefile.conf

PROG = mod_cap_ether.so

SRCS = ./ether_cap.cpp

LIBS += $(LIB_THREAD)

STGLIBS = common

include ../../Makefile.in

