###############################################################################
# $Id: Makefile,v 1.7 2008/12/04 17:06:56 faust Exp $
###############################################################################

include ../../../../../Makefile.conf

PROG = mod_cap_bpf.so

SRCS = ./ether_cap.cpp 

STGLIBS = -lstg_common

LIBS += $(LIB_THREAD)

include ../../Makefile.in

