###############################################################################
# $Id: Makefile,v 1.3 2007/05/08 14:29:21 faust Exp $
###############################################################################

LIB_NAME = stglogger
PROG = lib$(LIB_NAME)

SRCS = logger.cpp

INCS = logger.h

include ../Makefile.in
