###############################################################################
# $Id: Makefile,v 1.4 2008/12/04 17:05:21 faust Exp $
###############################################################################

include ../../../../../Makefile.conf

PROG = mod_cap_divert.so

SRCS = ./divert_cap.cpp 

LIBS += $(LIB_THREAD)

STGLIBS = common

include ../../Makefile.in

