###############################################################################
# $Id: Makefile,v 1.16 2010/03/04 10:47:45 faust Exp $
###############################################################################

include ../../../../../Makefile.conf

PROG = mod_store_files.so

SRCS = ./file_store.cpp

STGLIBS = -lconffiles -lstg_common -lstg_locker -lstg_crypto

include ../../Makefile.in

