###############################################################################
# $Id: Makefile,v 1.6 2010/01/21 13:02:12 faust Exp $
###############################################################################

LIB_NAME = stgscriptexecuter

SRCS = scriptexecuter.cpp

INCS = scriptexecuter.h

include ../Makefile.in
