#!/bin/sh

#   $Author: nobunaga $
#   $Revision: 1.2 $
#   $Date: 2008/01/05 12:11:02 $
######################################################

OS=unknown
sys=`uname -s`
release=`uname -r | cut -b1`
BUILD_DIR=`pwd`
CONFFILE="../../Makefile.conf"
PREFIX="/"
BIN_MODE=0755
DATA_MODE=0644
OWNER=root

if [ -z $1 ]
then
    MAKEOPTS="-j1"
    CFLAGS="-O2"
else
    if [ "$1" = "debug" ]
    then
        DEFS="-DDEBUG"
        MAKEOPTS="-j1"
        CFLAGS="-g3"
    else
        MAKEOPTS="-j1"
        CFLAGS="-O2"
    fi
fi

if [ "$sys" = "Linux" ]
then
    OS=linux
    release=""
    ETC_DIR="./inst/linux/etc/stargazer"
fi

if [ "$sys" = "FreeBSD" ]
then
    case $release in
        4) OS=bsd;;
        5) OS=bsd5;;
        6) OS=bsd5;;	
        *) OS=unknown;;
    esac
    ETC_DIR="./inst/freebsd/etc/stargazer"
fi

if [ "$OS" = "unknown" ]
then 
    echo "#############################################################################"
    echo "# Sorry, but sgconf currently supported by Linux, FreeBSD 4.x, 5.x, 6.x  #"
    echo "#############################################################################"
    exit 1
fi

echo "#############################################################################"
echo "       Building sgconf for $sys $release"
echo "#############################################################################"

STG_LIBS="conffiles.lib
	  crypto.lib 
	  common.lib 
	  srvconf.lib"

if [ "$OS" = "linux" ]
then
    DEFS="$DEFS -DLINUX"
    LIB_THREAD=-lpthread
    SHELL="/bin/bash"
else
    if [ "$OS" = "bsd" ]
    then
        DEFS="$DEFS -DFREE_BSD"
    else
        DEFS="$DEFS -DFREE_BSD5"
    fi
    SHELL="/usr/local/bin/bash"
    LIB_THREAD=-lc_r
fi

echo -n "Checking for -lexpat... "
echo "int main() { return 0; }" > build_check.c
gcc build_check.c -lexpat -o fake > /dev/null 2> /dev/null
if [ $? != 0 ]
then
    CHECK_EXPAT=no
    echo "no"
else
    CHECK_EXPAT=yes
    echo "yes"
fi
rm -f fake
rm -f build_check.c

if [ "$CHECK_EXPAT" != "yes" ]
then
    echo "-lexpat not found!"
    exit 1
fi

echo "OS=$OS" > $CONFFILE
echo "STG_TIME=no" >> $CONFFILE
echo "DIR_BUILD=$BUILD_DIR" >> $CONFFILE
echo "DIR_LIB=\$(DIR_BUILD)/../../lib" >> $CONFFILE
echo "DIR_LIBSRC=\$(DIR_BUILD)/../../stglibs" >> $CONFFILE
echo "DIR_INCLUDE=\$(DIR_BUILD)/../../include" >> $CONFFILE
echo "CHECK_EXPAT=$CHECK_EXPAT" >> $CONFFILE
echo "DEFS=$DEFS" >> $CONFFILE
echo -n "STG_LIBS=" >> $CONFFILE
for lib in $STG_LIBS
do
    echo -n "$lib " >> $CONFFILE
done
echo "" >> $CONFFILE
echo "SHELL=$SHELL" >> $CONFFILE
echo "CFLAGS=$CFLAGS" >> $CONFFILE
echo "PREFIX=$PREFIX" >> $CONFFILE
echo "BIN_MODE=$BIN_MODE" >> $CONFFILE
echo "DATA_MODE=$DATA_MODE" >> $CONFFILE
echo "OWNER=$OWNER" >> $CONFFILE
echo "ETC_DIR=$ETC_DIR" >> $CONFFILE

gmake $MAKEOPTS

