###############################################################################
# $Id: Makefile,v 1.6 2009/03/03 15:50:15 faust Exp $
###############################################################################

LIB_NAME = stgibpp

SRCS = array.cpp \
       blob.cpp \
       database.cpp \
       date.cpp \
       dbkey.cpp \
       _dpb.cpp \
       events.cpp \
       exception.cpp \
       _ibpp.cpp \
       _ibs.cpp \
       _rb.cpp \
       row.cpp \
       service.cpp \
       _spb.cpp \
       statement.cpp \
       time.cpp \
       _tpb.cpp \
       transaction.cpp \
       user.cpp

INCS = ibpp.h 

LIB_DEFS = -DIBPP_LINUX

LIBS = -lfbclient
       
include ../Makefile.in
