###############################################################################
# $Id: Makefile,v 1.2 2008/12/04 17:11:55 faust Exp $
###############################################################################

LIB_NAME = stg_locker
PROG = lib$(LIB_NAME)

SRCS = stg_locker.cpp

INCS = stg_locker.h

LIBS=$(LIB_THREAD)

include ../Makefile.in
