###############################################################################
# $Id: Makefile,v 1.7 2010/02/16 11:41:00 faust Exp $
###############################################################################

include ../../../../../Makefile.conf

LIBS += $(LIB_THREAD)

PROG = mod_remote_script.so

SRCS = ./rscript.cpp \
       ./nrmap_parser.cpp

STGLIBS = -lstg_common -lstg_crypto

include ../../Makefile.in

