###############################################################################
# $Id: Makefile,v 1.11 2010/08/18 07:47:03 faust Exp $
###############################################################################

LIB_NAME = stgia
PROG = lib$(LIB_NAME)

SRCS = ia.cpp

INCS = ia.h

STGLIBS = -lstgcommon \
	  -lstgcrypto
LIBS = $(LIB_THREAD)

include ../Makefile.in
