###############################################################################
# $Id: Makefile,v 1.2 2005/10/11 12:18:55 nobunaga Exp $
###############################################################################

#LIB_NAME = includes

#INCS = *.h
#include ../Makefile.in

all:
	echo hi

install:
	echo install