###############################################################################
# $Id: Makefile,v 1.11 2010/08/18 07:47:03 faust Exp $
###############################################################################

LIB_NAME = stgia

SRCS = ia.cpp

INCS = ia.h

STGLIBS = -lstgcrypto

LIBS = $(LIB_THREAD)

LIB_INCS = -I ../crypto.lib/include \
	   -I ../common.lib/include

include ../Makefile.in
