###############################################################################
# $Id: Makefile,v 1.2 2008/12/04 17:11:55 faust Exp $
###############################################################################

LIB_NAME = stglocker
PROG = lib$(LIB_NAME)

SRCS = locker.cpp

INCS = locker.h

LIBS = $(LIB_THREAD)

include ../Makefile.in
