/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "RFC1213-MIB"
 * 	found in "RFC1213-MIB.asn1"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_TcpConnEntry_H_
#define	_TcpConnEntry_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include "IpAddress.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TcpConnEntry */
typedef struct TcpConnEntry {
	INTEGER_t	 tcpConnState;
	IpAddress_t	 tcpConnLocalAddress;
	long	 tcpConnLocalPort;
	IpAddress_t	 tcpConnRemAddress;
	long	 tcpConnRemPort;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TcpConnEntry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TcpConnEntry;

#ifdef __cplusplus
}
#endif

#endif	/* _TcpConnEntry_H_ */
