###############################################################################
# $Id: Makefile,v 1.5 2009/10/09 07:15:48 nobunaga Exp $
###############################################################################

LIB_NAME = stgcrypto
PROG = lib$(LIB_NAME)

SRCS = ag_md5.cpp \
	blowfish.cpp

INCS = ag_md5.h \
	blowfish.h

include ../Makefile.in
