###############################################################################
# $Id: Makefile,v 1.5 2009/10/09 07:15:48 nobunaga Exp $
###############################################################################

LIB_NAME = stgcrypto

SRCS = ag_md5.c \
	blowfish.c \
	bfstream.cpp

INCS = ag_md5.h \
	blowfish.h \
	bfstream.h

include ../Makefile.in
